# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__, np.show_config)

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [7]:
x=np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [8]:
import numpy as np
x=np.zeros(10)
print(x.size,x.itemsize)

10 8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [10]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x=np.zeros(10)
x[4]=1

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [13]:
x=np.arange(start=10,stop=49,step=1)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [14]:
print(x[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [17]:
x=np.array([0,1,2,3,4,5,6,7,8])
print(x.reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [21]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [36]:
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [24]:
print(np.random.random((3,3,3,)))

[[[0.17921233 0.96286572 0.20814686]
  [0.32248748 0.10806752 0.61325643]
  [0.14322269 0.83683649 0.92198803]]

 [[0.1793703  0.44323295 0.81680507]
  [0.55581818 0.78730957 0.34030028]
  [0.11616162 0.5547444  0.82861139]]

 [[0.25538465 0.96304388 0.04414914]
  [0.865886   0.17142268 0.84656302]
  [0.64521393 0.75050807 0.19566769]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [26]:
x=np.random.random((10,10))
print(x)
print(x.min(),x.max())

[[0.85584195 0.98009483 0.4208689  0.19416522 0.79137012 0.3737904
  0.97672327 0.03346651 0.48362246 0.10824035]
 [0.3161949  0.70449386 0.72024791 0.47752311 0.18000078 0.54043266
  0.02859718 0.59087992 0.29041254 0.33263615]
 [0.00119224 0.91108706 0.96163237 0.49016924 0.71173391 0.58278868
  0.15993905 0.01592523 0.71795334 0.57574272]
 [0.3702825  0.78336061 0.34325041 0.75726202 0.02303173 0.8229282
  0.781016   0.66353263 0.91729857 0.57306892]
 [0.39893977 0.23521225 0.49583284 0.78585449 0.30043005 0.39512366
  0.53111126 0.95097494 0.52194998 0.1576172 ]
 [0.07057302 0.58509823 0.4457157  0.16310552 0.32890817 0.76039426
  0.37666175 0.41204561 0.27896316 0.05554223]
 [0.64128485 0.52773888 0.7842776  0.40480363 0.21793052 0.83738863
  0.88189144 0.7513516  0.67730188 0.97750924]
 [0.00716173 0.92761166 0.53268496 0.80973445 0.0155283  0.98026531
  0.53300759 0.56293743 0.73108114 0.93324481]
 [0.19466717 0.68794037 0.3511865  0.18541461 0.61710333 0.8832019
  0.88778816 0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [39]:
x = np.random.random(30)
print(x.mean())

0.4839635060556698


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [32]:
n=3
border_array = np.ones((n, n), dtype = int)
border_array[1:-1, 1:-1] = 0
print(border_array)
x=np.array([1,1,1,1,0,1,1,1,1,])
print(x.reshape(3,3))

[[1 1 1]
 [1 0 1]
 [1 1 1]]
[[1 1 1]
 [1 0 1]
 [1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [46]:
array=[1,1,1,1]
print(np.pad(array, (3,3), 'constant', constant_values=(0)))

[0 0 0 1 1 1 1 0 0 0]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [47]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [49]:
a = np.array([1,2,3,4])
print(np.diag(a,-1))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [57]:
x = np.zeros((8,8),dtype=int)
x[1::2, ::2] = 1
x[::2,1::2] = 1
for i in range(8):
        for j in range(8):
            print(x[i][j], end =" ") 
        print() 

0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [58]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [17]:
import numpy as np
n = 8
x=[1,0]
y=[0,1]
array=[]
for i in range(n):
    if i%2==0:
        array=np.concatenate((array,np.tile(x,4)))
    else:
        array=np.concatenate((array,np.tile(y,4)))
print(array)
print(np.reshape(array, (8, 8)))

[1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0.
 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1.
 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1.]
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [19]:
x= np.random.random((3,3))
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.91868694 0.28749163 0.33380754]
 [0.71146084 0.51820613 0.42817522]
 [0.86318682 0.30910707 0.56660969]]
[[1.         0.         0.0733781 ]
 [0.67169259 0.36551999 0.22288441]
 [0.9120714  0.03424525 0.44220554]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [20]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [25]:
arr1 = np.random.random((5,3))
arr2 = np.random.random((3,2))
print(arr1)
print(arr2)
print(np.dot(arr1,arr2))

[[0.32948062 0.11750042 0.09267603]
 [0.55638499 0.68286192 0.11891684]
 [0.27044412 0.83976014 0.99031793]
 [0.40701886 0.82844726 0.47383219]
 [0.56781723 0.96590767 0.04119956]]
[[0.1059698  0.15895416]
 [0.77087013 0.78401467]
 [0.69074251 0.2004418 ]]
[[0.18950784 0.16307052]
 [0.66749879 0.64764937]
 [1.36005962 0.89987359]
 [1.009053   0.80918792]
 [0.83321914 0.85580081]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [33]:
a = np.random.random(size=10)
a[3:7] = np.negative(a[3:7])
print(a)

[ 0.04072879  0.81663299  0.31284167 -0.58227865 -0.96063189 -0.36108878
 -0.2927493   0.02306121  0.75887561  0.16639582]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [37]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [39]:
Z = arange(10)
Z**Z
Z_2 = 2 << Z >> 2
Z_2
print([bin(z) for z in Z_2])
print([bin(z) for z in 2 << Z_2])
print([bin(z) for z in Z_2])
Z<Z>Z

['0b0', '0b1', '0b10', '0b100', '0b1000', '0b10000', '0b100000', '0b1000000', '0b10000000', '0b100000000']
['0b10', '0b100', '0b1000', '0b100000', '0b1000000000', '0b100000000000000000', '0b0', '0b0', '0b0', '0b0']
['0b0', '0b1', '0b10', '0b100', '0b1000', '0b10000', '0b100000', '0b1000000', '0b10000000', '0b100000000']


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [42]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\JYOTIM\AppData\Local\Temp/ipykernel_12852/548293649.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\JYOTIM\AppData\Local\Temp/ipykernel_12852/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [44]:
arr = np.random.random((3,3))
print(arr)
arr = np.round(arr,2)
print(arr) 

[[0.60179017 0.1579073  0.92078526]
 [0.48332579 0.054089   0.96884753]
 [0.31583329 0.45168466 0.12752743]]
[[0.6  0.16 0.92]
 [0.48 0.05 0.97]
 [0.32 0.45 0.13]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [48]:
arr1 = np.arange(10)
arr2= np.arange(20)
arr3=np.intersect1d(arr1,arr2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
#defaults = np.seterr(all="ignore")
#with np.errstate(divide='ignore')

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [49]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\JYOTIM\AppData\Local\Temp/ipykernel_12852/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [51]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday,today,tomorrow)

2022-08-08 2022-08-09 2022-08-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [52]:
a= np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [60]:
A = np.ones(3)*1
print(A)
B = np.ones(3)*2
print(B)
C = np.ones(3)*3
print(C)
print(np.add(A,B,out=B))
print(np.divide(A,2,out=A))
np.negative(A,out=A)
np.dot(A,B)

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]
[3. 3. 3.]
[0.5 0.5 0.5]


-4.5

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [63]:
Z= np.random.uniform(0,100,10)
print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))

[81.93253723 97.63772574 24.63177663 78.61730184 63.37850856 31.60149309
  9.8635223  75.39679196 87.06614393 13.10130643]
[81. 97. 24. 78. 63. 31.  9. 75. 87. 13.]
[81. 97. 24. 78. 63. 31.  9. 75. 87. 13.]
[81. 97. 24. 78. 63. 31.  9. 75. 87. 13.]
[81 97 24 78 63 31  9 75 87 13]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [67]:
arr=[0,1,2,3,4]
x=np.tile(arr,5)
print(np.reshape(x,(5,5)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [72]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=int)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [75]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [76]:
x= np.random.random(10)
x.sort()
print(x)

[0.09731239 0.1824969  0.20989831 0.236772   0.26894842 0.31549322
 0.51030911 0.52660949 0.68062935 0.72451207]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [78]:
a = np.array([1, 2, 3, 4])
print(np.add.reduce(a))

10


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [84]:
A = np.random.randint(0,2,10)
B = np.random.randint(0,2,10)

print(B)
print(A)

equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

[1 1 1 1 1 1 1 0 1 1]
[1 0 1 0 1 1 1 1 1 0]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [7]:
import numpy as np
a= np.zeros(10)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [15]:
z= np.random.randint(-10,10,(10,2))
print(z)
x,y = z[:,0], z[:,1]
print(x,y)
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
poles = np.c_[r,t]
print(poles)

[[  5   7]
 [ -9   9]
 [  1   1]
 [  9  -9]
 [ -7   1]
 [ -3  -1]
 [ -2 -10]
 [  8  -3]
 [  3  -6]
 [  4  -2]]
[ 5 -9  1  9 -7 -3 -2  8  3  4] [  7   9   1  -9   1  -1 -10  -3  -6  -2]
[[ 8.60232527  0.95054684]
 [12.72792206  2.35619449]
 [ 1.41421356  0.78539816]
 [12.72792206 -0.78539816]
 [ 7.07106781  2.9996956 ]
 [ 3.16227766 -2.8198421 ]
 [10.19803903 -1.76819189]
 [ 8.54400375 -0.35877067]
 [ 6.70820393 -1.10714872]
 [ 4.47213595 -0.46364761]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [18]:
a=np.random.random(10)
print(a)
a[a.argmax()]=0
print(a)

[0.5129449  0.6743713  0.47507497 0.81064056 0.08079425 0.46762294
 0.94374067 0.64718637 0.45113068 0.09479985]
[0.5129449  0.6743713  0.47507497 0.81064056 0.08079425 0.46762294
 0.         0.64718637 0.45113068 0.09479985]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [20]:

Z=np.zeros((10,10), [('x',float),('y',float)])
print(Z)
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]]
[[(0.        , 0.        ) (0.11111111, 0.       

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [24]:
Y = np.random.randint(0,11,10)
X = np.random.randint(11,22,10)
print(Y.reshape(1,10))
Y = np.tile(Y,(10,1))
print(Y,X)
X  = np.tile(X,(10,1)).T
print(X)
C = 1/(X - Y)
C

[[8 1 9 8 0 9 9 1 7 8]]
[[8 1 9 8 0 9 9 1 7 8]
 [8 1 9 8 0 9 9 1 7 8]
 [8 1 9 8 0 9 9 1 7 8]
 [8 1 9 8 0 9 9 1 7 8]
 [8 1 9 8 0 9 9 1 7 8]
 [8 1 9 8 0 9 9 1 7 8]
 [8 1 9 8 0 9 9 1 7 8]
 [8 1 9 8 0 9 9 1 7 8]
 [8 1 9 8 0 9 9 1 7 8]
 [8 1 9 8 0 9 9 1 7 8]] [11 17 16 12 15 15 11 15 21 16]
[[11 11 11 11 11 11 11 11 11 11]
 [17 17 17 17 17 17 17 17 17 17]
 [16 16 16 16 16 16 16 16 16 16]
 [12 12 12 12 12 12 12 12 12 12]
 [15 15 15 15 15 15 15 15 15 15]
 [15 15 15 15 15 15 15 15 15 15]
 [11 11 11 11 11 11 11 11 11 11]
 [15 15 15 15 15 15 15 15 15 15]
 [21 21 21 21 21 21 21 21 21 21]
 [16 16 16 16 16 16 16 16 16 16]]


array([[0.33333333, 0.1       , 0.5       , 0.33333333, 0.09090909,
        0.5       , 0.5       , 0.1       , 0.25      , 0.33333333],
       [0.11111111, 0.0625    , 0.125     , 0.11111111, 0.05882353,
        0.125     , 0.125     , 0.0625    , 0.1       , 0.11111111],
       [0.125     , 0.06666667, 0.14285714, 0.125     , 0.0625    ,
        0.14285714, 0.14285714, 0.06666667, 0.11111111, 0.125     ],
       [0.25      , 0.09090909, 0.33333333, 0.25      , 0.08333333,
        0.33333333, 0.33333333, 0.09090909, 0.2       , 0.25      ],
       [0.14285714, 0.07142857, 0.16666667, 0.14285714, 0.06666667,
        0.16666667, 0.16666667, 0.07142857, 0.125     , 0.14285714],
       [0.14285714, 0.07142857, 0.16666667, 0.14285714, 0.06666667,
        0.16666667, 0.16666667, 0.07142857, 0.125     , 0.14285714],
       [0.33333333, 0.1       , 0.5       , 0.33333333, 0.09090909,
        0.5       , 0.5       , 0.1       , 0.25      , 0.33333333],
       [0.14285714, 0.07142857, 0.1666666

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [25]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
#np.set_printoptions(threshold=np.nan)
#Z = np.zeros((int(1e4),int(1e4)))

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [34]:
arr = np.random.uniform(0,10,10)
scalar = 5
print(arr)
arr_1 = np.abs(arr - scalar)
print(arr_1)
ind = arr_1.argmin()
print(ind)

print(arr[ind])

[2.69015061 9.3953222  6.87563398 1.87846602 1.49529832 8.12954513
 7.97160687 2.57331056 0.26223785 2.39967847]
[2.30984939 4.3953222  1.87563398 3.12153398 3.50470168 3.12954513
 2.97160687 2.42668944 4.73776215 2.60032153]
2
6.875633975881006


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [37]:
import numpy as np
Z=np.zeros(10, [('position',[('x', float),('y', float)]),('color',[ ('r', float),('g', float),('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [42]:
arr = np.random.random((100,2))
#print(arr)
X,Y = np.atleast_2d(arr[:,0],arr[:,1])
#print(X,Y)
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.26404593 0.74373866 ... 1.17615042 0.32001642 0.57476705]
 [0.26404593 0.         0.4925408  ... 1.00186608 0.06354685 0.66261891]
 [0.74373866 0.4925408  0.         ... 0.63947971 0.45766934 0.88186978]
 ...
 [1.17615042 1.00186608 0.63947971 ... 0.         0.9989154  0.95580597]
 [0.32001642 0.06354685 0.45766934 ... 0.9989154  0.         0.71936108]
 [0.57476705 0.66261891 0.88186978 ... 0.95580597 0.71936108 0.        ]]
[[0.         0.23698833 0.26837307 0.41168634 0.78075495 0.29428302
  0.27390745 0.7497321  0.81451284 0.1099697 ]
 [0.23698833 0.         0.3740506  0.48056849 0.57951667 0.4398005
  0.08194283 0.56913017 0.83109757 0.13664755]
 [0.26837307 0.3740506  0.         0.14494047 0.72594167 0.08243376
  0.34415932 0.66359844 0.55169133 0.26678466]
 [0.41168634 0.48056849 0.14494047 0.         0.70956507 0.16740166
  0.43164754 0.63226013 0.40713038 0.39498466]
 [0.78075495 0.57951667 0.72594167 0.70956507 0.         0.80683989
  0.51377366 0.10010863 0.783

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [48]:
Z=np.arange(10, dtype=np.float32)
print(Z.astype(np.float32, copy=False))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [51]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",")
print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [52]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [54]:
sigma,myu = 1.0,0.0
X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
Gaussian = np.exp(-(D-myu)**2/(2*sigma**2))
print(Gaussian)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [65]:
n = 10
p=3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n),replace=True),p)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [66]:
X = np.random.rand(5, 10)
print(X)
Y = X - X.mean(axis = 1,keepdims = True)
#print(Y)
X.mean(axis = 1).reshape(-1,1) == X.mean(axis = 1,keepdims =True)

[[0.0010972  0.19105276 0.62707977 0.75000858 0.5503755  0.91048214
  0.62764372 0.98540165 0.17725974 0.35295417]
 [0.92205473 0.02408297 0.82645066 0.5832216  0.25818268 0.53444229
  0.93103822 0.96334166 0.85661997 0.35967878]
 [0.71376584 0.44519945 0.80160269 0.93767152 0.2105857  0.49662249
  0.16536758 0.48419923 0.33733415 0.07015659]
 [0.82183075 0.01287992 0.81487128 0.86317116 0.11961652 0.7932476
  0.30876774 0.10656367 0.72537369 0.82427129]
 [0.93057347 0.52529929 0.75468139 0.37658404 0.88642078 0.47073101
  0.02287059 0.95178297 0.17844271 0.7458567 ]]


array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [11]:
import numpy as np
print("Original array:\n")
nums = np.random.randint(0,10,(3,3))
print(nums[nums[:,0].argsort()])

Original array:

[[9 3 9]
 [8 7 9]
 [7 8 3]]

Sort the said array by the nth column: 
[[7 8 3]
 [8 7 9]
 [9 3 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [13]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print((~Z.any(axis=0)).any())

[[8 1 6]
 [5 7 0]
 [1 6 3]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [14]:
arr = np.array([12, 40, 65, 78, 10, 99, 30])
x = 85
difference_array = np.absolute(arr-x)
print(arr[difference_array.argmin()])

78


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [16]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A,B)
it = np.nditer([A,B,None])
print(it)
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0]
 [1]
 [2]] [[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [22]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z)

[0 1 2 3 4 5 6 7 8 9]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [28]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
print(np.bincount(I, minlength=len(Z)))
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3 0 3 7 7 8 3 1 7 4 1 1 1 9 7 0 1 4 6 2]
[2 5 1 3 2 0 1 4 1 1]
[3. 6. 2. 4. 3. 1. 2. 5. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [29]:
print(Z,I)
np.add.at(Z, I, 1)
print(Z)

[3. 6. 2. 4. 3. 1. 2. 5. 2. 2.] [3 0 3 7 7 8 3 1 7 4 1 1 1 9 7 0 1 4 6 2]
[ 5. 11.  3.  7.  5.  1.  3.  9.  3.  3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [33]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
#print(I)
colors = np.unique(I.reshape(-1, 3), axis=0)
#print(colors)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [34]:
A = np.random.randint(0,10,(3,4,3,4))
print(A)
sum = A.sum(axis=(-2,-1))
print(sum)

[[[[8 0 7 2]
   [9 6 2 7]
   [2 0 7 2]]

  [[0 0 4 5]
   [1 0 2 6]
   [2 3 2 0]]

  [[3 2 5 1]
   [0 4 2 0]
   [8 8 4 7]]

  [[3 7 6 1]
   [7 8 0 6]
   [2 6 4 1]]]


 [[[0 2 2 6]
   [5 4 4 1]
   [0 3 9 1]]

  [[6 1 3 0]
   [6 4 2 9]
   [8 9 0 9]]

  [[7 1 9 6]
   [0 5 2 6]
   [0 2 3 8]]

  [[3 6 3 7]
   [3 5 5 9]
   [3 3 9 5]]]


 [[[2 6 1 4]
   [8 0 4 3]
   [8 2 2 7]]

  [[6 2 6 2]
   [6 5 9 2]
   [1 6 5 3]]

  [[7 8 6 9]
   [1 5 8 0]
   [4 4 7 8]]

  [[9 5 4 9]
   [1 1 2 0]
   [0 6 4 7]]]]
[[52 25 44 51]
 [37 57 49 61]
 [47 53 67 48]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [38]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
#print(D,S,D_sums,D_counts)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.53379919 0.36041758 0.41713545 0.60272052 0.24706582 0.39851816
 0.56657394 0.40999068 0.47522097 0.59877235]
0    0.533799
1    0.360418
2    0.417135
3    0.602721
4    0.247066
5    0.398518
6    0.566574
7    0.409991
8    0.475221
9    0.598772
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [40]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))
print(A,B,np.diag(np.dot(A, B)))
# Fast version
np.sum(A * B.T, axis=1)


[[0.11208099 0.07030107 0.22724522 0.6473572  0.45780679]
 [0.1266703  0.87988291 0.10505944 0.84442197 0.65386651]
 [0.44208483 0.8010837  0.30642046 0.14377893 0.01762048]
 [0.88516909 0.37928602 0.9504209  0.84205523 0.17594085]
 [0.81597053 0.28672289 0.99594713 0.84736193 0.58913813]] [[7.08235351e-01 1.54959702e-01 3.91808877e-01 1.89844183e-01
  7.22807871e-01]
 [1.84765747e-04 5.09008646e-01 1.41034847e-01 3.85639006e-01
  8.96716565e-01]
 [7.34874394e-01 4.48063168e-01 3.12523755e-01 6.51066965e-01
  7.23086621e-01]
 [3.04428614e-01 6.04715847e-01 9.94696789e-01 8.91327079e-02
  4.96085611e-01]
 [7.79201023e-01 1.44339710e-01 2.86278869e-01 4.87886128e-01
  6.91394336e-01]] [0.80018698 1.11958431 0.53001796 1.0939931  2.39474596]


array([0.80018698, 1.11958431, 0.53001796, 1.0939931 , 2.39474596])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [41]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [46]:
A = np.ones((5,5,3))
print(A)

B =np.ones((5,5))
print(B)
print(A * B[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [47]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [54]:
faces = np.random.randint(0,100,(10,3))
print(faces)
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
print(F)
F = F.reshape(len(F)*3,2)
print(F)
F = np.sort(F,axis=1)
print(F)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
print(G)
G = np.unique(G)
print(G)

[[28 59 66]
 [98 68 66]
 [37 16 37]
 [68  3  4]
 [ 4 70 99]
 [30 88 26]
 [ 2 16 50]
 [13 88 20]
 [86 19 62]
 [ 7 73 91]]
[[28 59 59 66 66 28]
 [98 68 68 66 66 98]
 [37 16 16 37 37 37]
 [68  3  3  4  4 68]
 [ 4 70 70 99 99  4]
 [30 88 88 26 26 30]
 [ 2 16 16 50 50  2]
 [13 88 88 20 20 13]
 [86 19 19 62 62 86]
 [ 7 73 73 91 91  7]]
[[28 59]
 [59 66]
 [66 28]
 [98 68]
 [68 66]
 [66 98]
 [37 16]
 [16 37]
 [37 37]
 [68  3]
 [ 3  4]
 [ 4 68]
 [ 4 70]
 [70 99]
 [99  4]
 [30 88]
 [88 26]
 [26 30]
 [ 2 16]
 [16 50]
 [50  2]
 [13 88]
 [88 20]
 [20 13]
 [86 19]
 [19 62]
 [62 86]
 [ 7 73]
 [73 91]
 [91  7]]
[[28 59]
 [59 66]
 [28 66]
 [68 98]
 [66 68]
 [66 98]
 [16 37]
 [16 37]
 [37 37]
 [ 3 68]
 [ 3  4]
 [ 4 68]
 [ 4 70]
 [70 99]
 [ 4 99]
 [30 88]
 [26 88]
 [26 30]
 [ 2 16]
 [16 50]
 [ 2 50]
 [13 88]
 [20 88]
 [13 20]
 [19 86]
 [19 62]
 [62 86]
 [ 7 73]
 [73 91]
 [ 7 91]]
[[(28, 59)]
 [(59, 66)]
 [(28, 66)]
 [(68, 98)]
 [(66, 68)]
 [(66, 98)]
 [(16, 37)]
 [(16, 37)]
 [(37, 37)]
 [( 3, 68)]
 [( 3,

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [57]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
print(np.arange(len(C)))
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[0 1 2 3 4 5 6]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [65]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    print(ret)
    #print(ret[n:],ret[:-n])
    ret[n:] = ret[n:] - ret[:-n]
    #print(ret[n:])
    print(ret[n-1:])
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[  0.   1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91.
 105. 120. 136. 153. 171. 190.]
[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45. 48. 51. 54.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [69]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    print(shape,strides)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

(8, 3) (4, 4)
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [74]:
Z = np.random.randint(0,2,10)
print(Z)
print(np.logical_not(Z, out=Z))
Z = np.random.uniform(-1.0,1.0,10)
print(Z)
print(np.negative(Z, out=Z))

[1 0 1 0 1 0 0 1 0 0]
[0 1 0 1 0 1 1 0 1 1]
[-0.53308549  0.87964475 -0.62911083  0.6565142   0.99015184 -0.37252179
  0.68977289  0.29410134 -0.2403482   0.25709434]
[ 0.53308549 -0.87964475  0.62911083 -0.6565142  -0.99015184  0.37252179
 -0.68977289 -0.29410134  0.2403482  -0.25709434]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [81]:
def distance(P0, P1, p):
    T = P1 - P0
    #print(P1)
    #print(P0)
    print(T)
    L = (T**2).sum(axis=1)
    print(L)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[[ -6.42184428   7.29463348]
 [ -7.34173679  18.31835071]
 [-13.96115007  10.86762821]
 [  4.72945694   0.69234817]
 [  2.81819217  -3.56042589]
 [ -5.68781921 -11.06263038]
 [ 14.14013258  -4.00910057]
 [ -5.97009419   9.9531625 ]
 [-10.88500496  -9.35016123]
 [ -9.41081668   2.6936307 ]]
[ 94.4517616  389.4630719  313.01905423  22.84710889  20.61883961
 154.73307821 216.01623691 134.7074684  205.90884801  95.819117  ]
[5.45727099 4.99138689 0.15574104 5.00990414 5.08888606 3.5512808
 4.15819035 0.54018116 5.08337184 2.1399582 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [82]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ -1.47890088   4.39274227]
 [  6.73160254   2.01822461]
 [  5.53773009  -2.3145086 ]
 [  2.05680561   8.4955332 ]
 [ -4.95149525 -13.18584047]
 [ -3.01995628   2.96997595]
 [ 14.40022716  -0.84241407]
 [ -0.06397879  -2.17484558]
 [  7.56062358   1.95490571]
 [ -2.59518356  -1.36906503]]
[ 21.48333245  49.38770339  36.02340456  76.40453367 198.38369405
  17.94089306 208.07620373   4.73404659  60.98468533   8.60931675]
[[ -1.47890088   4.39274227]
 [  6.73160254   2.01822461]
 [  5.53773009  -2.3145086 ]
 [  2.05680561   8.4955332 ]
 [ -4.95149525 -13.18584047]
 [ -3.01995628   2.96997595]
 [ 14.40022716  -0.84241407]
 [ -0.06397879  -2.17484558]
 [  7.56062358   1.95490571]
 [ -2.59518356  -1.36906503]]
[ 21.48333245  49.38770339  36.02340456  76.40453367 198.38369405
  17.94089306 208.07620373   4.73404659  60.98468533   8.60931675]
[[ -1.47890088   4.39274227]
 [  6.73160254   2.01822461]
 [  5.53773009  -2.3145086 ]
 [  2.05680561   8.4955332 ]
 [ -4.95149525 -13.18584047]
 [ -3.0

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [83]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 0 9 3 9 3 5 7 4 5]
 [8 3 5 9 1 8 7 8 1 0]
 [2 1 4 2 2 0 1 7 9 9]
 [5 7 7 0 4 9 0 6 6 2]
 [8 2 3 4 0 0 8 9 4 7]
 [9 3 1 6 4 3 8 2 2 3]
 [8 3 7 1 7 6 0 5 8 3]
 [1 5 5 5 6 7 9 2 9 9]
 [8 3 3 9 5 3 7 8 6 0]
 [7 8 4 0 7 9 2 6 3 8]]
[[0 0 0 0 0]
 [0 8 0 9 3]
 [0 8 3 5 9]
 [0 2 1 4 2]
 [0 5 7 7 0]]


C:\Users\JYOTIM\AppData\Local\Temp/ipykernel_7480/1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [86]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [88]:
Z = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(Z)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [89]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [91]:
from numpy.lib.stride_tricks import sliding_window_view 
Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[4 4 1]
   [0 4 1]
   [3 3 4]]

  [[4 1 2]
   [4 1 2]
   [3 4 1]]

  [[1 2 1]
   [1 2 4]
   [4 1 4]]

  [[2 1 0]
   [2 4 2]
   [1 4 2]]

  [[1 0 0]
   [4 2 2]
   [4 2 1]]

  [[0 0 3]
   [2 2 1]
   [2 1 3]]

  [[0 3 2]
   [2 1 3]
   [1 3 2]]

  [[3 2 0]
   [1 3 2]
   [3 2 1]]]


 [[[0 4 1]
   [3 3 4]
   [1 2 2]]

  [[4 1 2]
   [3 4 1]
   [2 2 3]]

  [[1 2 4]
   [4 1 4]
   [2 3 3]]

  [[2 4 2]
   [1 4 2]
   [3 3 0]]

  [[4 2 2]
   [4 2 1]
   [3 0 2]]

  [[2 2 1]
   [2 1 3]
   [0 2 2]]

  [[2 1 3]
   [1 3 2]
   [2 2 1]]

  [[1 3 2]
   [3 2 1]
   [2 1 2]]]


 [[[3 3 4]
   [1 2 2]
   [0 4 2]]

  [[3 4 1]
   [2 2 3]
   [4 2 3]]

  [[4 1 4]
   [2 3 3]
   [2 3 0]]

  [[1 4 2]
   [3 3 0]
   [3 0 3]]

  [[4 2 1]
   [3 0 2]
   [0 3 2]]

  [[2 1 3]
   [0 2 2]
   [3 2 0]]

  [[1 3 2]
   [2 2 1]
   [2 0 4]]

  [[3 2 1]
   [2 1 2]
   [0 4 1]]]


 [[[1 2 2]
   [0 4 2]
   [1 1 4]]

  [[2 2 3]
   [4 2 3]
   [1 4 0]]

  [[2 3 3]
   [2 3 0]
   [4 0 1]]

  [[3 3 0]
   [3 0 3]
   [0 1 3]]

  [[3 0 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [98]:
M = np.array([[2,3,4], [3,45,8], [34,7,0.8], [21,31,41]])

S = np.matmul(M,M.T)

print( S)

[[  29.    173.     92.2   299.  ]
 [ 173.   2098.    423.4  1786.  ]
 [  92.2   423.4  1205.64  963.8 ]
 [ 299.   1786.    963.8  3083.  ]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [99]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [100]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [101]:
def iterate(Z):

    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [102]:
print (Z[np.argpartition(-Z,n)[:n]])

[[[0 0 1 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 1 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 1 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 1 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 1 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 1 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [103]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [104]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [105]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.2 s ± 246 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
570 ms ± 44.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
391 ms ± 9.44 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [108]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [109]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 2 2]
 [2 3 3]
 [4 3 3]
 [4 0 0]
 [0 1 4]
 [0 2 4]
 [4 2 3]
 [3 4 4]
 [4 2 4]
 [3 1 3]]
[[0 2 2]
 [2 3 3]
 [4 3 3]
 [4 0 0]
 [0 1 4]
 [0 2 4]
 [4 2 3]
 [3 4 4]
 [4 2 4]
 [3 1 3]]
[[0 2 2]
 [2 3 3]
 [4 3 3]
 [4 0 0]
 [0 1 4]
 [0 2 4]
 [4 2 3]
 [3 4 4]
 [4 2 4]
 [3 1 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [110]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [111]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [112]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)    

array([[0.35294067, 0.64062987, 0.1369811 , 0.53740343, 0.52213332,
        0.46252495, 0.47191857, 0.20641198, 0.22766719, 0.0142698 ],
       [0.51000852, 0.92572694, 0.19794127, 0.77656203, 0.75449633,
        0.66836067, 0.6819347 , 0.29827072, 0.32898505, 0.02062023],
       [0.20536935, 0.37277013, 0.07970665, 0.31270466, 0.30381928,
        0.26913432, 0.27460029, 0.12010714, 0.13247513, 0.00830332],
       [0.5192611 , 0.94252149, 0.20153233, 0.79065043, 0.76818442,
        0.68048608, 0.69430637, 0.30368195, 0.3349535 , 0.02099432],
       [0.51861145, 0.94134231, 0.20128019, 0.78966125, 0.76722335,
        0.67963473, 0.69343772, 0.30330202, 0.33453445, 0.02096806],
       [0.0749798 , 0.13609737, 0.02910068, 0.11416763, 0.1109236 ,
        0.09826022, 0.10025583, 0.04385079, 0.04836631, 0.00303152],
       [0.26833996, 0.48706938, 0.10414641, 0.40858656, 0.39697674,
        0.35165663, 0.35879858, 0.15693454, 0.17309483, 0.01084929],
       [0.31855528, 0.57821623, 0.1236356

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [115]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [116]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [117]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.10566465  0.31639189]
